app = "cicd-673"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  SPRING_PROFILES_ACTIVE = "prod"

[org]
  name = "personal"

[vm]
  size = "performance-1x"
  memory = "2048mb"

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 443

  [[services.ports]]
    port = 80