github:
  app:
    private-key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEowIBAAKCAQEA4ISk2+oDO2qRr/oX2fhxu6FxfSf0wS4jZYn41tF7f/z46SH5
      m/XKldCYN+CUvbDH/eciH0+kvo0t3pwj7CAoRygrZNQLlcc7+Wr6HH4+Li9+QWKh
      sJ50UqqpvIusBiaf9Cq3roLHfaMQYkOvyvrTCczeEqvTI0E28wwPT3qgt44spVLP
      8uojXYfYnQi7Z1wXo7WJGm1hdD7jUhT69fUQbLAzNk6mgmjSx1/yiZHwlE7PzClE
      Pr09dqmUtJGr0jgwV6V0Beugs5Z5Jozo1MuxisRUbBKgXoz/FnTlpDUitzy9+Dr3
      jf6d5wlSoeRlpV5dL9QfkJHuacsOomzWCR8ZvQIDAQABAoIBAQCzFbq2W5PWaevp
      VXB/AegeROlUbnGRQa8kSAh/uTpsXalhtCL43vaHx4oTUAT0xbTQdvPFy+5ZvBzx
      atRQfVoDYCw00dqnzvKswULdRWltx55Ko1Tbn5ijc9POPA6sHVULGqPHBDQBp/bi
      mqD3JFj/gTVF6V6RyWv+NAlmWScnITcLPdVHqOpYZCS2pSLLjQq+NWLCy5ZsmpQ2
      /aj4DquvwhI1VbHV1ofsKgNp22S+epaEL5JZrIgsXmcNEaAZ1efj11PUpG31hhgw
      gTTy8Kz4xCz35pLD2iZXQqjPweDGENaJVBiJ4D+aRMcwW+5vlGlz8vt9uWZy76xh
      f9x/WibhAoGBAPjRAK6nFXU4GsljL1NdU7rGpyMsZhyyhbDcFHk8MrLBYVcInrEZ
      QkcopKu/MHZPkCek2iA8ALSCn1pwF+Jr6++tSHlribOWcc4oTevAP7NlMcaRxEJ0
      mVz6EnkjXWj5evdwOG9dY00hdf14yP5xlIKQZeAZu2mAV3QTwVKrXDBVAoGBAOcA
      DaAzBAz2v6UdbUAEHh/Wqi/2RgZcYFV0EXYCEB1gfXn6bxb7smPwkE+NX2c1l1ym
      Y/c6zMjY5Z/BGcgW/O8xPsAP9SWr7NOqiqISBE/dIzkTy90TqpD/hT9QoulqYSV2
      V7lVTCK2FroDLEPfHfU9+ENPV769tZn5RALkg4vJAoGAe8uJGlyZSYQLl81Ye5LA
      mPpDqDVr7LVJ3Q/yw8sWsmeSpbntMtINbtgi7iym0QaPA5p6yHTyKN2gqV+CEq59
      afd+SqMdlROyNc9JzZUOXJRpqpFV43ad42usi0b0L8mIy9myyn3dbT/Ls7xHzIj4
      SenMNi63Vyt6148IrbgCmy0CgYANTH58U5OPH4GHAvuwLMyDLrubiUUcxqKxKL58
      mb/NwSlYJWfR3em2QTo9qjjs2zP8nIOyzwrNIVeO6/INB+3F44LmUcTeR1iaEv5q
      ODlRU7zcY1xgPOqb8Gn+bCkE4R/4pSiFvfhlIzCJwvcAbU7vOIMbdOzrSUa0N5qH
      xBoiqQKBgEvfo7sLRKWREtUYabG9ndbu2G0yNMDW4nZFgLkw26/7JNhK2t36PNU/
      2e1gkS1zBm8TXXfcjkc/2KCk+wEe1j8U1lldH0ZUeAXh3C4j/xzn01v/axf4YY2H
      wyDvF/vIRo3EzZVK3+ayQ0YVHdLfQjzptntAOC1pxHNpnI3guZgB
      -----END RSA PRIVATE KEY-----